version: 2
updates:

- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: weekly
  cooldown:
    default-days: 3
  allow:
    - dependency-type: "direct"
  open-pull-requests-limit: 0

- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: weekly
    day: monday
  cooldown:
    default-days: 7
  groups:
    codeql:
      patterns:
        - "github/codeql-action*"
    other-actions:
      patterns:
        - "*"
      exclude-patterns:
        - "github/codeql-action*"
  open-pull-requests-limit: 10
  labels:
    - "chore"
    - "dependencies"
    - "github_actions"
