schema: ./transmission_schema.json5

data_type_short_desc: high-voltage transmission lines ordinance

query_templates:
  - "site:municode.com {jurisdiction}, electrical transmission line"
  - "site:codelibrary.amlegal.com {jurisdiction}, electrical transmission line"
  - "filetype:pdf {jurisdiction}, electric transmission line ordinance"
  - "{jurisdiction}, high voltage transmission line zoning ordinance"
  - "{jurisdiction}, electric transmission line siting code"
  - "{jurisdiction}, overhead electric utility line ordinance"
  - "{jurisdiction}, transmission line right-of-way regulation"

website_keywords:
  pdf: 92160
  transmission: 46080
  ordinance: 23040
  zoning: 11520
  utility: 5760
  electric: 5760
  right-of-way: 1440
  overhead: 720
  permit: 720
  land use: 720
  municipal: 360
  county: 360
  code of ordinances: 360
  ordinance code: 360
  land use code: 360
  conditional use permit: 180
  special use permit: 180
  statute: 180
  administrative code: 180
  government: 180

heuristic_keywords: true
heuristic_keywords:
  good_tech_acronyms:
    - "kv"
    - "hvdc"
    - "ehv"
    - "uhv"
    - "cpcn"
  good_tech_phrases:
    - "high voltage"
    - "high-voltage"
    - "extra high voltage"
    - "extra-high voltage"
    - "bulk transmission"
    - "electric transmission"
    - "69 kv"
    - "115 kv"
    - "138 kv"
    - "161 kv"
    - "230 kv"
    - "345 kv"
    - "500 kv"
    - "765 kv"
  not_tech_words:
    - "transmission fluid"
    - "radio tower"
    - "gas transmission"


collection_prompts: true

cache_llm_generated_content: true
